### ISSUE TITLE
INFOGRAFIA_ANALISIS DEL WEBBINAR

### ISSUE THREAD

**Issue by ka194** [SistemasTecTlaxiaco/actividad-1-infografia-ka194-1#1]
[INFOGRAFIA _ ANALISIS DEL WEBBINAR.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-ka194-1/files/14284837/INFOGRAFIA._.ANALISIS.DEL.WEBBINAR.pdf)

**Comment by yanet02** [comment]
CALIFICADO DE ACUERDO A LA RÚBRICA

Partes de la infografía: 4
Coherencia y pertinencia: 3
Organización de la información: 3
Diseño y composición de la infografía: 4
Creatividad: 4
Total=18 
**CALIFICACIÓN=18/20**
_Muy bien trabajo, te faltó agregar bibliografías y las fases._

**Comment by josealfredo79** [comment]
Bien hecho y revisado,...
